services:
  app:
    image: bdnosql-api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=app-database
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"